# Data: https://www.kaggle.com/jsphyg/weather-dataset-rattle-package?select=weatherAUS.csv

# Import data

In [123]:
import pandas as pd 
import seaborn as sns

In [124]:
data = pd.read_csv('weatherAUS.csv')

In [125]:
data.tail()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
142188  2017-06-20    Uluru      3.5     21.8       0.0          NaN   
142189  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
142190  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
142191  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
142192  2017-06-24    Uluru      7.8     27.0       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
142188       NaN           E           31.0        ESE  ...        27.0   
142189       NaN           E           31.0         SE  ...        24.0   
142190       NaN         NNW           22.0         SE  ...        21.0   
142191       NaN           N           37.0         SE  ...        24.0   
142192       NaN          SE           28.0        SSE  ...        24.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
142188       1024.7       1021.2       NaN       NaN      9.4     20.9   
142189       1024.6       1020.3       NaN       NaN     10.1     22.4   
142190       1023.5       1019.1       NaN       NaN     10.9     24.5   
142191       1021.0       1016.8       NaN       NaN     12.5     26.1   
142192       1019.4       1016.5       3.0       2.0     15.1     26.0   

        RainToday  RISK_MM  RainTomorrow  
142188         No      0.0            No  
142189         No      0.0            No  
142190         No      0.0            No  
142191         No      0.0            No  
142192         No      0.0            No  

[5 rows x 24 columns]

In [126]:
data.corr()

MinTemp   MaxTemp  Rainfall  Evaporation  Sunshine  \
MinTemp        1.000000  0.736267  0.104255     0.467261  0.072961   
MaxTemp        0.736267  1.000000 -0.074839     0.588915  0.469967   
Rainfall       0.104255 -0.074839  1.000000    -0.064549 -0.227525   
Evaporation    0.467261  0.588915 -0.064549     1.000000  0.366607   
Sunshine       0.072961  0.469967 -0.227525     0.366607  1.000000   
WindGustSpeed  0.177285  0.067690  0.133497     0.203001 -0.032831   
WindSpeed9am   0.176005  0.014680  0.086816     0.193936  0.008040   
WindSpeed3pm   0.175749  0.050800  0.057759     0.128895  0.056012   
Humidity9am   -0.234211 -0.505432  0.223725    -0.505890 -0.491603   
Humidity3pm    0.005999 -0.509270  0.255312    -0.392785 -0.629122   
Pressure9am   -0.451260 -0.332293 -0.168085    -0.269907  0.040959   
Pressure3pm   -0.461623 -0.427279 -0.126728    -0.293160 -0.020464   
Cloud9am       0.077625 -0.289865  0.198195    -0.185032 -0.675610   
Cloud3pm       0.020489 -0.279053  0.171993    -0.184287 -0.704202   
Temp9am        0.901813  0.887020  0.011477     0.545497  0.291139   
Temp3pm        0.708865  0.984562 -0.079178     0.574275  0.490180   
RISK_MM        0.124743 -0.044208  0.308557    -0.043498 -0.294973   

               WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  \
MinTemp             0.177285      0.176005      0.175749    -0.234211   
MaxTemp             0.067690      0.014680      0.050800    -0.505432   
Rainfall            0.133497      0.086816      0.057759     0.223725   
Evaporation         0.203001      0.193936      0.128895    -0.505890   
Sunshine           -0.032831      0.008040      0.056012    -0.491603   
WindGustSpeed       1.000000      0.604837      0.686419    -0.215461   
WindSpeed9am        0.604837      1.000000      0.519971    -0.270807   
WindSpeed3pm        0.686419      0.519971      1.000000    -0.145942   
Humidity9am        -0.215461     -0.270807     -0.145942     1.000000   
Humidity3pm        -0.026663     -0.031607      0.015903     0.667388   
Pressure9am        -0.457891     -0.227923     -0.295567     0.139519   
Pressure3pm        -0.412922     -0.174916     -0.254988     0.186955   
Cloud9am            0.071235      0.024280      0.052780     0.452182   
Cloud3pm            0.109088      0.053584      0.025269     0.358043   
Temp9am             0.150258      0.129298      0.163601    -0.472826   
Temp3pm             0.032970      0.005108      0.028567    -0.499777   
RISK_MM             0.162923      0.069404      0.049240     0.172417   

               Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
MinTemp           0.005999    -0.451260    -0.461623  0.077625  0.020489   
MaxTemp          -0.509270    -0.332293    -0.427279 -0.289865 -0.279053   
Rainfall          0.255312    -0.168085    -0.126728  0.198195  0.171993   
Evaporation      -0.392785    -0.269907    -0.293160 -0.185032 -0.184287   
Sunshine         -0.629122     0.040959    -0.020464 -0.675610 -0.704202   
WindGustSpeed    -0.026663    -0.457891    -0.412922  0.071235  0.109088   
WindSpeed9am     -0.031607    -0.227923    -0.174916  0.024280  0.053584   
WindSpeed3pm      0.015903    -0.295567    -0.254988  0.052780  0.025269   
Humidity9am       0.667388     0.139519     0.186955  0.452182  0.358043   
Humidity3pm       1.000000    -0.027449     0.051840  0.517037  0.523270   
Pressure9am      -0.027449     1.000000     0.961348 -0.130081 -0.148139   
Pressure3pm       0.051840     0.961348     1.000000 -0.061152 -0.084963   
Cloud9am          0.517037    -0.130081    -0.061152  1.000000  0.604118   
Cloud3pm          0.523270    -0.148139    -0.084963  0.604118  1.000000   
Temp9am          -0.221467    -0.422773    -0.470325 -0.137843 -0.127869   
Temp3pm          -0.557989    -0.287301    -0.389863 -0.302520 -0.318254   
RISK_MM           0.313183    -0.163673    -0.164184  0.198095  0.234814   

                Temp9am   Temp3pm   RISK_MM  
MinTemp        0.901813  

In [127]:
X = data.iloc[:,:-1]

In [128]:
X.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  
0      0.0  
1      0.0  
2      0.0  
3      1.0  
4      0.2  

[5 rows x 23 columns]

In [129]:
y = data.iloc[:,-1]

In [130]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: RainTomorrow, dtype: object

# Handling missing data - Numeric type

In [131]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [132]:
#X.dtypes

In [133]:
numerical_cols = list(np.where((X.dtypes == np.int64) | (X.dtypes == np.float64))[0])

In [134]:
imp_mean.fit(X.iloc[:,numerical_cols])

SimpleImputer()

In [135]:
X.iloc[:,numerical_cols] = imp_mean.transform(X.iloc[:,numerical_cols])

### Handling missing string data

In [136]:
string_cols = list(np.where((X.dtypes == np.object))[0])

In [137]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [138]:
imp_mean.fit(X.iloc[:,string_cols])

SimpleImputer(strategy='most_frequent')

In [139]:
X.iloc[:,string_cols] = imp_mean.transform(X.iloc[:,string_cols])

# One Hot encoder method

In [140]:
def OneHotEncoderMethod(indices, data):
    from sklearn.compose import ColumnTransformer
    from sklearn.preprocessing import OneHotEncoder
    columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(),indices )], remainder='passthrough')
    return columnTransformer.fit_transform(data)

# Label encoding method

In [141]:
def LabelEncoderMethod(series):
    from sklearn import preprocessing
    le = preprocessing.LabelEncoder()
    return le.fit_transform(series) 

# Label encoding target feature

In [142]:
y = LabelEncoderMethod(y)

# Encoding selection for X

In [143]:
def EncodingSelection(X, threshold=10):
    # Step 01 : Select the string col
    string_cols = list(np.where((X.dtypes == np.object))[0])
    one_hot_encoding_indices = []
    
    # Step 02: The number of categoty is 2 and more than threshold, label encode
    for col in string_cols:
        lenght = len(pd.unique(X[X.columns[col]]))
        if lenght == 2 or lenght > threshold:
            X[X.columns[col]] = LabelEncoderMethod(X[X.columns[col]])
        else:
            one_hot_encoding_indices.append(col)
            
    # Step 03: One hot encode otherwise 
    X = OneHotEncoderMethod(one_hot_encoding_indices, X)
    return X

In [144]:
X = EncodingSelection(X)

In [145]:
X.shape

(142193, 23)

# Feature selection

In [146]:
from sklearn.feature_selection import SelectKBest, chi2

In [147]:
from sklearn import preprocessing

In [148]:
MMS = preprocessing.MinMaxScaler()

In [149]:
X1 = MMS.fit_transform(X)

In [150]:
kbest = SelectKBest(chi2,k=5)

In [151]:
selection = kbest.fit(X1,y)

In [152]:
scores = selection.scores_

In [171]:
for i in sorted_scores:
    print ('{0:.10f}'.format(i)) 

0.3240258472
2.0239855988
3.3998480174
14.4304187803
23.3833175184
35.3260440639
46.3778834304
50.1487007502
50.3829041733
74.0417640946
122.6872264546
122.6896860575
157.6794979143
172.2261129221
284.1025812089
481.9740845396
649.2752204363
1028.8204495892
1190.5670665674
1415.9775291935
2250.8683684183
2934.6949412418
10406.6992321974


In [154]:
best_features = scores.argsort()[-10:]

In [155]:
scores.argsort()

array([ 1,  0, 19,  5, 10,  9,  2, 11, 12,  7,  3, 16, 15, 20,  8, 13,  4,
        6, 17, 18, 14, 22, 21], dtype=int64)

In [156]:
best_features

array([20,  8, 13,  4,  6, 17, 18, 14, 22, 21], dtype=int64)

In [164]:
abc = scores.argsort()[:-10]

In [165]:
abc

array([ 1,  0, 19,  5, 10,  9,  2, 11, 12,  7,  3, 16, 15], dtype=int64)

In [157]:
X1.shape

(142193, 23)

In [167]:
np.delete(X1, abc, axis=1).shape

(142193, 10)

In [160]:
print(X1)

[[0.11528384 0.04166667 0.51650943 ... 0.52207294 0.         0.        ]
 [0.11557496 0.04166667 0.375      ... 0.57005758 0.         0.        ]
 [0.11586608 0.04166667 0.50471698 ... 0.54894434 0.         0.        ]
 ...
 [0.99912664 0.85416667 0.28537736 ... 0.57389635 0.         0.        ]
 [0.99941776 0.85416667 0.32783019 ... 0.60460653 0.         0.        ]
 [0.99970888 0.85416667 0.38443396 ... 0.60268714 0.         0.        ]]


In [170]:
sorted_scores = np.sort(scores)

# Train test split

In [106]:
import numpy as np
from sklearn.model_selection import train_test_split

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [108]:
print(X_train.shape)

(164, 199)


# Feature scaling

### Standardization: (X - mean(X)) / std(X)

### Normalization = (x - min(x)) / (max(x) - min(x))

In [109]:
from sklearn import preprocessing

In [112]:
sc = preprocessing.StandardScaler(with_mean=False)

In [113]:
sc.fit(X_train)

StandardScaler(with_mean=False)

In [114]:
X_train = sc.transform(X_train)

In [115]:
print(X_train.shape)

(164, 199)


In [116]:
X_test = sc.transform(X_test)

In [117]:
print(X_test.shape)

(41, 199)


#### The data is ready!!

# Building Linear model

In [122]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.09741670577134398

# Building Polynomial Linear regression model

In [123]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
model = LinearRegression()
poly = PolynomialFeatures(degree = 2)
X_train_poly = poly.fit_transform(X_train)
model.fit(X_train_poly,y_train)
X_test_poly = poly.fit_transform(X_test)
y_pred = model.predict(X_test_poly)
r2_score(y_test, y_pred)

-0.4531422286977287

# Building Decision Tree model

In [124]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth = 4)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.883961900453219

# Building Random forest Tree model

In [125]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators= 25, random_state = 10)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.9107611439295349

# Building AdaBoost model

In [126]:
from sklearn.ensemble import AdaBoostRegressor
model = AdaBoostRegressor(random_state=0, n_estimators=100)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.8806696893560713

# Building XGBoost model

In [128]:
import xgboost as xgb

model = xgb.XGBRegressor(
    n_estimators=100,
    reg_lambda=1,
    gamma=0,
    max_depth=3,
    learning_rate=0.05
)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

0.8947431439987505

# Building SVM model


In [129]:
from sklearn.svm import SVR
model = SVR()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

-0.02713944090388254