# Dataset: https://www.kaggle.com/nltkdata/movie-review

### Import the library 

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

### Import Data

In [2]:
data = pd.read_csv('movie_review.csv')

In [3]:
data.head()

fold_id cv_tag  html_id  sent_id  \
0        0  cv000    29590        0   
1        0  cv000    29590        1   
2        0  cv000    29590        2   
3        0  cv000    29590        3   
4        0  cv000    29590        4   

                                                text  tag  
0  films adapted from comic books have had plenty...  pos  
1  for starters , it was created by alan moore ( ...  pos  
2  to say moore and campbell thoroughly researche...  pos  
3  the book ( or " graphic novel , " if you will ...  pos  
4  in other words , don't dismiss this film becau...  pos

In [4]:
X = data.iloc[:,-2]

In [5]:
y = data.iloc[:,-1]

In [6]:
X

0        films adapted from comic books have had plenty...
1        for starters , it was created by alan moore ( ...
2        to say moore and campbell thoroughly researche...
3        the book ( or " graphic novel , " if you will ...
4        in other words , don't dismiss this film becau...
                               ...                        
64715    that lack of inspiration can be traced back to...
64716    like too many of the skits on the current inca...
64717    after watching one of the " roxbury " skits on...
64718     bump unsuspecting women , and . . . that's all .
64719    after watching _a_night_at_the_roxbury_ , you'...
Name: text, Length: 64720, dtype: object

## CountVectorizer

In [7]:
# from sklearn.feature_extraction.text import CountVectorizer
# corpus = ['This is the first document.',
#             'This document is the second document.',
#             'And this is the third one.',
#             'Is this the first document?']
# vectorizer = CountVectorizer()
# X = vectorizer.fit_transform(corpus)
# print(vectorizer.get_feature_names())
# print(X.toarray())

## Train test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

### TfidfVectorizer documentation 
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

### Working With Text Data tutorial 
https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html

In [9]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# corpus = ['This is the first document.',
#             'This document is the second document.',
#             'And this is the third one.',
#             'Is this the first document?']

# vectorizer = TfidfVectorizer()
# X = vectorizer.fit_transform(corpus)
# print(vectorizer.get_feature_names())

# print(X.toarray())

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X_train)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
from sklearn.svm import LinearSVC
model = LinearSVC()
model.fit(X_tfidf, y_train)

LinearSVC()

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
y_pred = model.predict(X_test)
accuracy_score(y_pred,y_test)

ValueError: could not convert string to float: 'van sant has made a boring film .'

In [19]:
X_test

54756                    van sant has made a boring film .
43964    " jawbreaker " is a pastiche , and not even an...
21339    both their choices were perhaps born of impati...
56309    `any given sunday' is a visual kaleidoscope th...
54493    clarence williams iii , who plays colonel fowl...
                               ...                        
52943    no , apparently they flip toward each other so...
63255    there's an ongoing feud between animal and his...
38239                 well , a few chuckles ensue anyway .
49833               how can you play death in human form ?
37394              it's too much to handle in one dosage .
Name: text, Length: 12944, dtype: object

In [20]:
Xtest_tfidf = vectorizer.fit_transform(X_test)

In [21]:
y_pred = model.predict(Xtest_tfidf)
accuracy_score(y_pred,y_test)

ValueError: X has 20818 features per sample; expecting 36615